import { Program } from "src/modules/plans/entities/plan.entity";

export const programs = [
  {
    title: 'Hogar Permanente Diamante',
    image:
      'https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?w=600&q=80',
    features: [
      'Habitación privada con baño independiente.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento previamente autorizadas.',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados.',
      'Toma de signos vitales.',
      'Apoyo en las actividades de la vida diaria.',
      'Vigilancia nocturna de comportamiento al dormir.',
      'Afiliación a seguro funerario si no lo posee.',
    ],
  },
  {
    title: 'Hogar Permanente Esmeralda',
    image:
      'https://images.unsplash.com/photo-1581579438747-1dc8d17bbce4?w=600&q=80',
    features: [
      'Habitación privada.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento previamente autorizadas.',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud.',
      'Terapeuta ocupacional.',
      'Dinámicas de integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Vigilancia nocturna.',
      'Afiliación a seguro funerario.',
    ],
  },
  {
    title: 'Hogar Permanente Oro',
    image:
      'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=600&q=80',
    features: [
      'Habitación privada.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento previamente autorizadas.',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas semanales de especialistas de la salud.',
      'Terapeuta ocupacional.',
      'Integración familiar los fines de semana.',
      'Suministro de medicamentos autorizados.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Vigilancia nocturna.',
      'Afiliación a seguro funerario.',
    ],
  },
  {
    title: 'Hogar Permanente VIP Compartido',
    image:
      'https://images.unsplash.com/photo-1516307365426-bea591f05011?w=600&q=80',
    features: [
      'Habitación compartida con baño compartido.',
      'Aire acondicionado.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento previamente autorizadas.',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas de especialistas de la salud.',
      'Terapeuta ocupacional.',
      'Integración familiar.',
      'Suministro de medicamentos autorizados.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Vigilancia nocturna.',
      'Afiliación a seguro funerario.',
    ],
  },
  {
    title: 'Hogar Permanente Compartido',
    image:
      'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=600&q=80',
    features: [
      'Habitación compartida con baño compartido.',
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento previamente autorizadas.',
      'Asistencia en comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería las 24 h.',
      'AMI, servicio de asistencia primaria y emergencias.',
      'Actividades recreativas todas las semanas.',
      'Visitas de especialistas de la salud.',
      'Terapeuta ocupacional.',
      'Integración familiar.',
      'Suministro de medicamentos autorizados.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Vigilancia nocturna.',
      'Afiliación a seguro funerario.',
    ],
  },
  {
    title: 'Hogar Vacaciones',
    image:
      'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?w=600&q=80',
    features: [
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento a la habitación diario.',
      'Cuidado de pertenencias.',
      'Lavado y planchado de ropa.',
      'Salidas con acompañamiento autorizadas.',
      'Comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería.',
      'AMI servicio de emergencias durante la estancia.',
      'Actividades recreativas.',
      'Vigilancia de toma de medicamentos.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Vigilancia nocturna.',
    ],
  },
  {
    title: 'Hogar Cuidado Diario',
    image:
      'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?w=600&q=80',
    features: [
      'Tres comidas principales y 2 meriendas.',
      'Aseo y mantenimiento diario.',
      'Cuidado de pertenencias.',
      'Salidas con acompañamiento autorizadas.',
      'Comunicación virtual con familiares.',
      'Acompañamiento de auxiliares de enfermería.',
      'AMI servicio de emergencias durante la estancia.',
      'Actividades recreativas.',
      'Vigilancia de toma de medicamentos.',
      'Toma de signos vitales.',
      'Apoyo en actividades de la vida diaria.',
      'Traslados desde y hacia su residencia (valor adicional).',
    ],
  },
];
